export const albumsActionTypes = {
    ADD_ALBUM: "ADD_ALBUM",
    ADD_ALBUMS: "ADD_ALBUMS",
    LOAD_ALBUMS_FROM_STORAGE: "LOAD_FROM_STORAGE",
    SET_USER_ALBUMS: "SET_USER_ALBUMS",
    SET_ALL_ALBUMS: "SET_ALL_ALBUMS",
    SET_ACTIVE_ALBUM: "SET_ACTIVE_ALBUM",
    UNSET_ACTIVE_ALBUM: "UNSET_ACTIVE_ALBUM",
}

export default albumsActionTypes;